import { LegalPage } from "../components/legal/LegalPage";

const sections = [
	{ id: "about", title: "1. Personal data we may collect", content: <><ul><li><strong>Account data:</strong> name, email address, phone number and authentication information.</li><li><strong>Profile data:</strong> profile picture, biography, professional title, role, institution and connection information.</li><li><strong>Workspace and learning data:</strong> courses created or joined, roles, classes, assignments and uploaded resources.</li><li><strong>Communications:</strong> messages, replies, reactions and personal messages where enabled.</li></ul></> },
	{ id: "collection", title: "How we collect data", content: <p>We may collect information directly from you, automatically through your use of the Platform, or from administrators who create or manage participants.</p> },
	{ id: "purposes", title: "Purposes and Lawful Bases", content: <><p>Depending on the circumstances, we may process personal data to create and manage accounts; authenticate users; provide learning services; manage workspaces and rooms; facilitate learning and communication; maintain and improve the Platform; provide support and notifications; secure the Platform; prevent abuse; and comply with legal obligations.</p><p>Where applicable, we process personal data under the lawful bases available to us, including performance of a contract, compliance with a legal obligation, legitimate interests, and consent.</p></> },
	{ id: "visibility", title: "Visibility and Sharing", content: <p>Information intentionally displayed in public profiles, public workspaces, public workspace activity or public professional links may be visible to other users or the public. Private account information should not be exposed through a public profile.</p> },
	{ id: "third-party", title: "Third-Party Services and International Transfers", content: <p>Vrede may use services such as hosting, analytics, email, authentication and infrastructure providers. Where a service provider processes personal data on Vrede's behalf, we seek appropriate contractual and security protections.</p> },
	{ id: "retention", title: "Data Retention", content: <p>We retain personal data only for as long as necessary to provide the Platform, meet legal obligations, resolve disputes, enforce agreements and protect our legitimate interests.</p> },
	{ id: "security", title: "Security Controls", content: <p>We use reasonable administrative, technical and organisational measures designed to protect personal data. No method of transmission or storage is completely secure.</p> },
	{ id: "rights", title: "Your Rights and Choices", content: <p>Depending on where you live, you may have rights to access, correct, delete or restrict the use of your personal data, object to certain processing, or request a copy of your information. Contact us at <a href="mailto:legal@vrede.app">legal@vrede.app</a> to exercise these rights.</p> },
	{ id: "cookies", title: "Cookies and Analytics", content: <p>We may use cookies and similar technologies to keep you signed in, remember preferences, understand usage and improve the Platform.</p> },
	{ id: "contact", title: "Contact Us", content: <p>Questions about this policy can be sent to <a href="mailto:legal@vrede.app">legal@vrede.app</a>.</p> },
	{ id: "changes", title: "Changes to this Policy", content: <p>We may update this policy from time to time. Any revised version will be posted on this page with an updated effective date.</p> },
] as const;

export default function PrivacyPolicy() {
	return <LegalPage title="Data Privacy Policy" date="September 23rd 2026" intro="This Data Privacy Policy explains how VREDE LTD (“Vrede”, “we”, “us” or “our”) collects, uses, stores, discloses and protects personal data when you use Vrede, the website vrede.app, the mobile application and related services. Vrede operates in Nigeria and intends this Policy to support compliance with the Nigeria Data Protection Act 2023 (“NDPA”) and applicable data-protection requirements." sections={sections} artPosition="left" />;
}
